function:
  handler: src/204-multistop-event-processor/index.handler
  name: 204-multistop-event-processor-${self:provider.stage}
  description: process and filters shipment apar table stream for 204 create shipment - ${self:provider.stage}
  runtime: nodejs18.x
  timeout: 500
  layers:
    - !Ref DWBackendLambdaLayer
  events:
    - stream:
        arn: ${ssm:/omni-live-204/${self:provider.stage}/consol-status/ddb.streamArn~true}
        batchSize: 5
        maximumRetryAttempts: 3
        bisectBatchOnFunctionError: true

  package:
    patterns:
      - '!**/*'
      - 'src/204-multistop-event-processor/index.js'
      - 'src/shared/constants/204_create_shipment.js'

  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    STAGE: ${self:provider.stage}
    STATUS_TABLE: ${ssm:/omni-204-create-shipment/${self:provider.stage}/status/ddb.name}
