---
function:
  name: omni-cw-to-wt-retrigger-process-${self:provider.stage}
  handler: src/cw-to-wt-retrigger-process/index.handler
  runtime: nodejs20.x
  timeout: 900
  layers:
    - { Ref: DWBackendLambdaLayer }
  package:
    include:
      - 'src/cw-to-wt-retrigger-process/**'
      - 'src/shared/**'
    exclude:
      - '**/*'
  events:
    - schedule: cron(*/30 * * * ? *) #cron for every 30 min
  environment:
    LOGS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/cw-to-wt/create-shipment/ddb.tableName}
