---
function:
  name: omni-cw-to-wt-create-shipment-${self:provider.stage}
  handler: src/cw-to-wt-create-shipment/index.handler
  runtime: nodejs18.x
  timeout: 900
  layers:
    - { Ref: DWBackendLambdaLayer }
  package:
    include:
      - 'src/cw-to-wt-create-shipment/**'
      - 'src/shared/**'
    exclude:
      - '**/*'
  events:
    - s3:
        bucket: ${ssm:/omni-dw/${self:provider.stage}/wms/bucket/name}
        event: s3:ObjectCreated:*
        rules:
          - prefix: CargoWiseOutbound/FederalSignal/
          - suffix: ${ssm:/wms-shipengine/${self:provider.stage}/file/suffix}
        existing: true
  environment:
    WT_URL: ${ssm:/omni-dw/${self:provider.stage}/createShipment/wt/url}
    LOGS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/re-create-shipment-logs/ddb.tableName}
    CUSTOMERS_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/customers/ddb.tableName}
    wt_soap_username: ${ssm:/omni-dw/${self:provider.stage}/wt/soap/username~true}
    wt_soap_password: ${ssm:/omni-dw/${self:provider.stage}/wt/soap/password~true}
