---
function:
    handler: src/ltl_batch_rating.handler
    layers:
        - { Ref: DWBackendLambdaLayer }
    name: ${self:service}-ltl-batch-rating-${self:provider.stage}
    description: LTL batch ration - ${self:provider.stage}
    runtime: nodejs18.x
    memorySize: 2048
    timeout: 900
    package:
        include:
            - src/ltl_batch_rating.js
            - shared/**
    # environment:
    #     NETSUITE_INTERCOMPANY_BASE_URL: ${ssm:/omni-dw/${self:provider.stage}/netsuit/intercompany/url}
    #     NETSUITE_INTERCOMPANY_ARN: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:service}-intercompany-cw-state-machine-${self:provider.stage}
