---
function:
    handler: src/ltl_batch_rating.handler
    layers:
        - { Ref: DWBackendLambdaLayer }
    name: ${self:service}-ltl-batch-rating-${self:provider.stage}
    description: LTL batch ration - ${self:provider.stage}
    runtime: nodejs18.x
    memorySize: 2048
    timeout: 900
    events:
        - sqs:
              arn: ${ssm:/omni-dw-api-services/${self:provider.stage}/ltl-batch-rating/file-queue-arn~true}
              batchSize: 1
              functionResponseType: ReportBatchItemFailures
    package:
        patterns:
            - src/ltl_batch_rating.js
            - shared/**
    environment:
        LTL_BATCH_RATING_STATE_MACHINE: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${self:service}-ltl-batch-rating-state-machine-${self:provider.stage}"
        BATCH_RATING_QUEUE: ${ssm:/omni-dw-api-services/${self:provider.stage}/ltl-batch-rating/file-queue-arn~true}