function:
  handler: src/shipment_detail_collector/index.handler
  name: ${self:service}-shipment-header-stream-${self:provider.stage}
  description: shipment header stream to dynamoDB - ${self:provider.stage}
  runtime: nodejs18.x
  timeout: 300
  layers:
    - !Ref DWBackendLambdaLayer
  memorySize: 512

  package:
    patterns:
      - "!**/*"
      - "src/shipment_detail_collector/index.js"
      - "src/shared/**"

  events:
    - stream: 
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.streamArn~true}
        batchSize: 5
        maximumRetryAttempts: 3
  environment:
    SHIPMENT_DETAILS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetails/table}
    SHIPMENT_DETAILS_HOUSEBILL_INDEX: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetails/houseBillKey/index}
    SHIPMENT_DETAILS_FILENUMBER_INDEX: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetails/FileNumber/index}
    REGION: ${self:provider.region}
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    SHIPPER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipper/ddb.tableName~true}
    CONSIGNEE_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consignee/ddb.tableName~true}
    SHIPMENT_DESC_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-desc/ddb.tableName~true}
    REFERENCE_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/references/ddb.tableName~true}
    SHIPMENT_MILESTONE_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-milestone/ddb.tableName~true}
    TRACKING_NOTES_TABLE_INDEXVALUE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/tracking-notes/ddb.orderNoIndex}
    TIMEZONE_MASTER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/timezone-master/ddb.tableName~true}
    SERVICE_LEVEL_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/servicelevels/ddb.tableName}
    MILESTONE_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/milestone/ddb.tableName}
    SHIPMENT_MILESTONE_DETAIL_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-milestone-detail/ddb.tableName}
    TRACKING_NOTES_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/tracking-notes/ddb.tableName~true}
    P44_LOCATION_UPDATE_TABLE: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/ddb.table_name}
    SHIPMENT_DETAILS_Collector_TABLE: ${ssm:/omni-dw/${self:provider.stage}/shipmentDetailsCollector/ddb.tableName}
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    REFERENCE_TABLE_INDEX: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/references/ddb.orderNoIndex}