---
stateMachine:
    name: ${self:service}-ltl-batch-rating-state-machine-${self:provider.stage}
    events:
        - sqs:
            arn: ${ssm:/omni-dw-api-services/${self:provider.stage}/ltl-batch-rating/file-queue-arn~true}
            batchSize: 10
            functionResponseType: ReportBatchItemFailures
    definition:
        Comment: "State machine to get ltl rating"
        StartAt: PublishEvents
        States:
            PublishEvents:
                Type: Task
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-ltl-batch-rating-${self:provider.stage}'
                Next: EndChoice
            EndChoice:
                Type: Choice
                Choices:
                    - Variable: $.hasMoreData
                      StringEquals: "false"
                      Next: SuccessState
                    - Variable: $.hasMoreData
                      StringEquals: "true"
                      Next: PublishEvents
            SuccessState:
                Type: Succeed
