204UpdateTableStreamDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: omni-dw-backend-204-update-table-stream-DLQ-${self:provider.stage}

204UpdateTableStreamQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: omni-dw-backend-204-update-table-stream-queue-${self:provider.stage}
    VisibilityTimeout: 500
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt 204UpdateTableStreamDLQ.Arn
      maxReceiveCount: 3

204UpdateTableStreamQueuePolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    Queues:
      - !GetAtt 204UpdateTableStreamQueue.QueueUrl
    PolicyDocument:
      Id: 204UpdateTableStreamQueuePolicy
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal: '*'
          Action: SQS:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn:
                - ${ssm:/omni-wt-rt-updates/${self:provider.stage}/confirmation-cost/sns.arn~true}
                - ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consol-stop-headers/sns.arn~true}
